name: Latest Grafana API compatibility check
on: [pull_request]

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      # pnpm action uses the packageManager field in package.json to
      # understand which version to install.
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build plugin
        run: pnpm run build

      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: |
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name "module.tsx" \))"
          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT

      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@is-compatible/v1.0.2
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: 'no'
          fail-if-incompatible: 'yes'
